[package]
org ="ballerinax"
name = "redis"
version ="0.99.1"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
path = "../redis-utils/target/redis-0.99.1-SNAPSHOT.jar"
groupId = "org.ballerinalang"
artifactId = "redis-utils"
version = "0.99.1"


