[package]
org="ballerinax"
name = "redis"
version="0.99.2"

[[platform.java11.dependency]]
path = "../redis-utils/target/redis-0.99.2-SNAPSHOT.jar"
groupId = "org.ballerinalang"
artifactId = "redis-utils"
module = "redis-utils" 
version="0.99.2"
