name: CI

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest
        
        strategy:
            matrix:
        
                redis:
                - '5.0'

        name: Redis ${{ matrix.redis }} on ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                java-version: 11
            - name: Setup redis
              uses: shogo82148/actions-setup-redis@v1
              with:
                redis-version: ${{ matrix.redis }}
                auto-start: "false"
            
            -  run: mvn clean install
            -  run: cd redis
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@swan-lake-connector-release
              with:
                  args:
                      build -c ./redis
              
              env: 
                  JAVA_HOME: /usr/lib/jvm/default-jvm
                  JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true
            - name: wget
              uses: wei/wget@v1
              with:
                  args: -qO- https://httpbin.org/get
