name: CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                java-version: 11 
            # Grant execute permission to the gradlew script
            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            # Build the project with Gradle
            - name: Build with Gradle
              env:
                packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
                packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
                JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true
              run: |
                ./gradlew build
            - name: Set Up Ballerina
              uses: ballerina-platform/setup-ballerina@v1
              with:
                version: 2201.5.0
            - name: Ballerina Build
              run: bal pack
              env:
                JAVA_HOME: /usr/lib/jvm/default-jvm 
                JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true
            - name: Ballerina Test 
              run: bal test redis
              env:
                JAVA_HOME: /usr/lib/jvm/default-jvm 
                JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true

            # Read the ballerina test results
            - name: Read Ballerina Test Results
              id: test_results
              run: |
                content=`cat ./redis/target/report/test_results.json`                
                content="${content//'%'/'%25'}"
                content="${content//$'\n'/'%0A'}"
                content="${content//$'\r'/'%0D'}"
                echo "::set-output name=testResultsJson::$content"

            # Print the code coverage information
            - name: Code Coverage
              run: |
                echo "Covered Code Lines : ${{fromJson(steps.test_results.outputs.testResultsJson).coveredLines}}"
                echo "Total Code Lines : $(expr ${{fromJson(steps.test_results.outputs.testResultsJson).missedLines}} + ${{fromJson(steps.test_results.outputs.testResultsJson).coveredLines}})"
                echo "Code Coverage Percentage : ${{fromJson(steps.test_results.outputs.testResultsJson).coveragePercentage}}"
