name: CI

on: [pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                java-version: 11 
            # Grant execute permission to the gradlew script
            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            # Build the project with Gradle
            - name: Build with Gradle
              env:
                packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
                packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
                JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true
              run: |
                ./gradlew build
            - name: Ballerina Download
              run: sudo wget https://dist.ballerina.io/downloads/2201.7.0/ballerina-2201.7.0-swan-lake.zip
            - name: Use Ballerina zip version
              run: sudo apt-get install -y unzip
            - run: sudo unzip ballerina-2201.7.0-swan-lake.zip
              env: 
                  JAVA_HOME: /usr/lib/jvm/default-jvm
                  JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true 
            - name: Ballerina Build 
              run: /home/runner/work/module-ballerinax-redis/module-ballerinax-redis/ballerina-2201.7.0-swan-lake/bin/bal build redis
